#!/usr/bin/env python3
"""
Clean up the guardian-vs.svg file to remove Cline references.
"""

from pathlib import Path

def clean_guardian_vs_svg():
    """Remove Cline references from guardian-vs.svg metadata."""
    svg_path = Path(__file__).parent / 'guardian-vs' / 'assets' / 'icons' / 'guardian-vs.svg'
    
    if not svg_path.exists():
        print(f"✗ File not found: {svg_path}")
        return False
    
    try:
        with open(svg_path, 'r') as f:
            content = f.read()
        
        # Replace Cline references with Guardian VS references
        updated_content = content.replace('cline-bot', 'guardian-vs')
        updated_content = updated_content.replace('"cline"', '"guardian"')
        updated_content = updated_content.replace('https://cline.bot', 'https://github.com/donatello-code/guardian-vs')
        updated_content = updated_content.replace('Font generated by IcoMoon.', 'Guardian VS icon font.')
        
        with open(svg_path, 'w') as f:
            f.write(updated_content)
        
        print(f"✓ Cleaned up {svg_path}")
        return True
        
    except Exception as e:
        print(f"✗ Failed to clean up SVG file: {e}")
        return False

def main():
    print("=== Cleaning up guardian-vs.svg file ===\n")
    
    if clean_guardian_vs_svg():
        print("\n✅ Successfully cleaned up guardian-vs.svg!")
        print("   - Replaced 'cline-bot' with 'guardian-vs'")
        print("   - Updated URLs")
        print("   - Updated description")
    else:
        print("\n✗ Failed to clean up SVG file")

if __name__ == '__main__':
    main()